=== diemenator/monmodel/model.xsd
<?xml version="1.1"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:simpleType name="Duration">
        <xs:restriction base="xs:string">
            <xs:pattern value="^(?:(\d+)h)?(?:(\d+)m)?(?:(\d+)s)?$"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="TemplateValue">
        <xs:restriction base="xs:string">
        </xs:restriction>
    </xs:simpleType>
    <xs:complexType name="AlertDefaults">
        <xs:all>
            <xs:element type="Duration" name="wait" minOccurs="0" maxOccurs="1"/>
            <xs:element type="Duration" name="repeat" minOccurs="0" maxOccurs="1"/>
        </xs:all>
    </xs:complexType>
    <xs:complexType name="TemplateValues">
        <xs:sequence>
            <xs:element name="add" minOccurs="0" maxOccurs="unbounded">
                <xs:annotation>
                    <xs:documentation>arbitrary elements</xs:documentation>
                </xs:annotation>
                <xs:complexType>
                    <xs:sequence>
                        <xs:any maxOccurs="unbounded" minOccurs="0"></xs:any>
                    </xs:sequence>
                    <xs:assert test="not(*/*)"/>
                    <xs:assert test="every $child in * satisfies ($child[(len(string(.)) > 0) and ])"/>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="Alert">
        <xs:all>
            <xs:element type="Duration" name="wait" minOccurs="0" maxOccurs="1"/>
            <xs:element type="Duration" name="repeat" minOccurs="0" maxOccurs="1"/>
            <xs:element type="xs:string" name="name" minOccurs="1">
                <xs:annotation>
                    <xs:documentation>optional if alert-defaults is defined
                    </xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element type="xs:string" name="text" minOccurs="1">
                <xs:annotation>
                    <xs:documentation>this appears as alert text body</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element type="xs:string" name="channel" minOccurs="1" maxOccurs="unbounded">
                <xs:annotation>
                    <xs:documentation>this specifies a name of notifications channel, defined
                        separately
                    </xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:all>
    </xs:complexType>
    <xs:complexType name="Metric">
        <xs:all>
            <xs:element type="xs:string" name="name" minOccurs="0">
                <xs:annotation>
                    <xs:documentation>grafana panel title
                    </xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="link" minOccurs="0">
                <xs:annotation>
                    <xs:documentation>this renders an arbitrary link</xs:documentation>
                </xs:annotation>
                <xs:complexType>
                    <xs:all>
                        <xs:element type="xs:string" name="text" minOccurs="1" maxOccurs="1"/>
                        <xs:element type="xs:string" name="href" minOccurs="1" maxOccurs="1"/>
                    </xs:all>
                </xs:complexType>
            </xs:element>
            <xs:element name="mlink" minOccurs="0">
                <xs:complexType>
                    <xs:all>
                        <xs:element type="xs:string" name="text" minOccurs="1" maxOccurs="1">
                            <xs:annotation>
                                <xs:documentation>this renders a link to another model
                                </xs:documentation>
                            </xs:annotation>
                        </xs:element>
                        <xs:element type="xs:string" name="id" minOccurs="1" maxOccurs="1"/>
                    </xs:all>
                </xs:complexType>
            </xs:element>
            <xs:element type="xs:string" name="query" minOccurs="0">
                <xs:annotation>
                    <xs:documentation>promql query, additional filters will be injected
                    </xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element type="xs:string" name="record" minOccurs="0">
                <xs:annotation>
                    <xs:documentation>metric name to record as result of query
                    </xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element type="xs:string" name="display" minOccurs="0">
                <xs:annotation>
                    <xs:documentation>grafana panel type: discrete, graph, heatmap, etc...
                    </xs:documentation>
                </xs:annotation>
            </xs:element>

            <xs:element name="threshold" minOccurs="0">
                <xs:annotation>
                    <xs:documentation>
                        defines a values range threshold
                    </xs:documentation>
                </xs:annotation>
                <xs:complexType>
                    <xs:all>
                        <xs:element name="alert" minOccurs="0">
                            <xs:complexType>
                                <xs:all>
                                    <xs:element type="xs:string" name="name" minOccurs="1">
                                        <xs:annotation>
                                            <xs:documentation>optional if alert-defaults is defined
                                            </xs:documentation>
                                        </xs:annotation>
                                    </xs:element>
                                    <xs:element type="xs:string" name="text" minOccurs="1">
                                        <xs:annotation>
                                            <xs:documentation>this appears as alert text body</xs:documentation>
                                        </xs:annotation>
                                    </xs:element>
                                    <xs:element type="xs:string" name="channel" minOccurs="0" maxOccurs="unbounded">
                                        <xs:annotation>
                                            <xs:documentation>this specifies a name of notifications channel, defined
                                                separately
                                            </xs:documentation>
                                        </xs:annotation>
                                    </xs:element>
                                    <xs:element type="xs:string" name="wait">
                                        <xs:annotation>
                                            <xs:documentation>defers notification: 5s, 1m, 10m, 1h, 1d...
                                            </xs:documentation>
                                        </xs:annotation>
                                    </xs:element>
                                    <xs:element type="xs:string" name="repeat">
                                        <xs:annotation>
                                            <xs:documentation>notification repeat interval: 5s, 1m, 10m, 1h, 1d...
                                            </xs:documentation>
                                        </xs:annotation>
                                    </xs:element>
                                </xs:all>
                            </xs:complexType>
                        </xs:element>
                        <xs:element type="xs:string" name="range"/>
                        <xs:element type="xs:float" name="weight">
                            <xs:annotation>
                                <xs:documentation>threshold boundaries</xs:documentation>
                            </xs:annotation>
                        </xs:element>
                    </xs:all>
                </xs:complexType>
            </xs:element>
            <xs:element type="xs:string" name="grafana-properties-json" minOccurs="0" maxOccurs="1">
                <xs:annotation>
                    <xs:documentation>if some tweaking is in order</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element type="Node" name="node" minOccurs="0" maxOccurs="1">
                <xs:annotation>
                    <xs:documentation>child node</xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:all>
    </xs:complexType>
    <xs:complexType name="Node">
        <xs:all>
            <xs:element type="xs:string" name="name" minOccurs="1" maxOccurs="1">
                <xs:annotation>
                    <xs:documentation>this becomes x-project-name label value for every recorded metric
                    </xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element type="xs:string" name="id" minOccurs="0" maxOccurs="1">
                <xs:annotation>
                    <xs:documentation>this becomes a dashboard id, available to mlink
                    </xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element type="xs:anyURI" name="scrape" maxOccurs="unbounded" minOccurs="0"/>
            <xs:element type="AlertDefaults" name="alert-defaults" maxOccurs="1" minOccurs="0"/>
            <xs:element type="TemplateValues" name="template-values" maxOccurs="1" minOccurs="0"/>
            <xs:element type="Metric" name="metric" minOccurs="0" maxOccurs="unbounded">
                <xs:annotation>
                    <xs:documentation>
                        <![CDATA[
                            renders a graph panel with metric
                        ]]>
                    </xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element type="Metric" name="template" minOccurs="0" maxOccurs="unbounded">
                <xs:annotation>
                    <xs:documentation><![CDATA[
every <add /> element denotes a templated metric render
every %ElementName% placeholder in definition's content is substituted with the string value of<ElementName>
                        ]]>
                    </xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:all>
    </xs:complexType>
    <xs:element name="node" type="Node">

    </xs:element>
</xs:schema>

=== diemenator/monmodel/example-model.xml
<?xml version="1.0" encoding="UTF-8" ?>
<node
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="model.xsd"
>
    <name>Test Dashboard</name>
    <scrape>http://asddds:8088</scrape>
    <alert-defaults>
        <wait>1m</wait>
        <repeat>4h</repeat>
    </alert-defaults>
    <template-values>
        <add><sys_title>System A</sys_title><sys_id>sys_a</sys_id><sys_range><![CDATA[ > 100 ]]></sys_range></add>
        <add><sys_title>System B</sys_title><sys_id>sys_b</sys_id><sys_range><![CDATA[ > 200 ]]></sys_range></add>
    </template-values>
    <template>
        <name>%sys_title% overview</name>
        <link>
            <text>wiki page</text>
            <href>https://asd.com/</href>
        </link>
        <mlink>
            <text>Other teams view</text>
            <id>Other System A</id>
        </mlink>
        <query><![CDATA[promql_query{env=prod}]]></query>
        <record>valid_name_with_labels{label_name_0="v1",label_name_1="%sys_id%"}</record>
        <display>graph</display>
        <threshold>
            <alert>
                <name>dla</name>
                <text>bla is experiencing dla with %sys_title%</text>
                <wait>1m</wait>
                <repeat>2h</repeat>
                <channel>Team1</channel>
                <channel>Team2</channel>
            </alert>
            <range>%sys_range%</range>
            <weight>1.0</weight>
        </threshold>
        <grafana-properties-json></grafana-properties-json>
        <node>
            <name>%sys_id% details</name>
            <metric>
                <node>
                    <name></name>
                </node>
            </metric>
            <!-- child node -->
        </node>
    </template>
</node>
